default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CleanCode_development
  username: ricardo
  password: pasword
  # password: Rails.application.credentials.dig(:postgres, :password, :development)
  host: localhost 
  port: 5432

test:
  <<: *default
  database: CleanCode_test


production:
  <<: *default
  database:  CleanCode_production
  username: CleanCode
  password: <%= ENV['CLEANCODE_DATABASE_PASSWORD'] %>
